services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  webapp:
    image: product-microservice:latest
    build: .
    env_file: .env.prod
    ports:
      - 8080:8080
    restart: always
    depends_on:
      db:
        condition: service_healthy
